//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeDrag.Drag {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Drag.IDrag")]
    public interface IDrag {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrag/calcDrag", ReplyAction="http://tempuri.org/IDrag/calcDragResponse")]
        string calcDrag(decimal cd, decimal area, decimal velocity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDrag/calcDrag", ReplyAction="http://tempuri.org/IDrag/calcDragResponse")]
        System.Threading.Tasks.Task<string> calcDragAsync(decimal cd, decimal area, decimal velocity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDragChannel : ConsumeDrag.Drag.IDrag, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DragClient : System.ServiceModel.ClientBase<ConsumeDrag.Drag.IDrag>, ConsumeDrag.Drag.IDrag {
        
        public DragClient() {
        }
        
        public DragClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DragClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DragClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DragClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string calcDrag(decimal cd, decimal area, decimal velocity) {
            return base.Channel.calcDrag(cd, area, velocity);
        }
        
        public System.Threading.Tasks.Task<string> calcDragAsync(decimal cd, decimal area, decimal velocity) {
            return base.Channel.calcDragAsync(cd, area, velocity);
        }
    }
}
